```{r}
# histograma
trees
hist(trees$Height)
hist(trees$Height, main = "Árvores", ylab = "Frequência", xlab = "Altura", col = "blue") # aqui foi definido o título o nome dos eixos, e a cor
hist(trees$Height, main = "Árvores", ylab = "Frequência", xlab = "Altura", col = "blue", density = 20, breaks = 20) # deixando a densidade da cor menor e também o gráfico com mais detalhes
```
```{r}
# usando a densidade para ver o mesmo gráfico
densidade = density(trees$Height)
plot(densidade)
```
```{r}
# gerando o histograma junto com a densidade.
hist(trees$Height, main = NULL, xlab = NULL, ylab = NULL)
par(new=T) # define que o próximo gráfico irá sobrepor o anterior
plot(densidade)
```
```{r}
# gráfico de dispersão
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main = "Árvores")
plot(trees$Girth, trees$Volume, main = "Árvores", ylab = "Circunferência", xlab = "Volume", col = "blue")
plot(trees$Girth, trees$Volume, main = "Árvores", ylab = "Circunferência", xlab = "Volume", col = "blue", pch = 20) # aqui só mudamos o pch, que serve para alterar o elemento gráfico
plot(trees$Girth, trees$Volume, main = "Árvores", ylab = "Circunferência", xlab = "Volume", col = "blue", pch = 20, type = "l") # aqui mudamos o tipo, passamos que será linhas
plot(jitter(trees$Girth), trees$Volume) # o jitter é uma 'tremulação', para que seja possível ver os valores que se sobrepoem.
```
```{r}
# adicionando leganda categórica
CO2
plot(CO2$conc, CO2$uptake, pch=20, col = CO2$Treatment)
legend("bottomright", legend = c("nonchilled","chilled"), cex = 1, fill = c("black", "red")) # aqui adicionamos a legenda, o primeiro parâmetro diz a posição, o segundo é os nomes que a vai conter na legenda, o terceiro é o tamanho da legenda, e o último é a cores que os parâmetros recebem. Para saber qual parâmetro colocar é só olhar qual aparece primeiro na base de dados, como o nonchilled apareceu primeiro, aqui também temos de colocar ele primeiro
```
```{r}
plot(trees) # aqui ele cria uma matriz de gráficos
```

```{r}
# dividindo a tela
split.screen(figs = c(2,2)) # definindo as dimensões da tela
screen(1) # escolhendo em qual tela irei colocar
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=T)
```

