```{r}
# importando dados, tendo strings vazias como NA e string como fatores.
dados = read.csv('Churn.csv', sep=";", na.strings = "", stringsAsFactors = T)
head(dados)
summary(dados) # trás um resumo dos dados
```

```{r}
# dando nome para as colunas
colnames(dados) = c("Id", "Score", "Estado", "Genero", "Idade", "Patrimonio","Saldo", "Produtos", "TemCartCredito", "Ativo", "Salario", "Saiu")
head(dados)
```
```{r}
# explorando dados, colunas categóricas
counts = table(dados$Estado)
barplot(counts, main="Estados", xlab="Estados") # tabela dos estados, passando o título e o nome do eixo x
counts = table(dados$Genero)
barplot(counts, main="Genero", xlab = "Generos") # tabela dos generos
```
```{r}
# explorando colunas numéricas
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)
```
```{r}
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```
```{r}
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```
```{r}
summary(dados$Salario)
boxplot(dados$Salario)
boxplot(dados$Salario, outline = F)
```
```{r}
# encontrando valores incompletos (NA)
dados[!complete.cases(dados),] # o ! serve como negação, o lado esquerdo da vírgula é para as linhas e o direito é para as colunas

```
```{r}
summary(dados$Salario)
median(dados$Salario, na.rm = T) # aqui se encontra a mediana, como existem valores (na) é preciso usar o na.rm como True, ou se não a função irá retornar (na) também.
dados[is.na(dados$Salario),]$Salario = median(dados$Salario, na.rm = T) # fazendo um teste lógico para encontrar os campos vazios e já substituir pela mediana.
dados[!complete.cases(dados$Salario),]
```
```{r}
# padrinização de gêneros
unique(dados$Genero) # retorna os valores que podem ter no gênero
summary(dados$Genero)
dados[is.na(dados$Genero) | dados$Genero == "M" ,]$Genero = "Masculino"  # aqui estamos trocando os valores vazios e os valores que estão com M, tudo para Masculino
dados[dados$Genero == "F" | dados$Genero == "Fem" ,]$Genero = "Feminino"
summary(dados$Genero)
# como dá para ver o termos ficaram zerados ao invés de serem retirados, e agora podemos retirar eles.
dados$Genero = factor(dados$Genero)
summary(dados$Genero)
```
```{r}
# mudando idades fora do dominio
summary(dados$Idade)
dados[dados$Idade<0 | dados$Idade>110 ,]$Idade # visualisando valores fora do dominio
dados[is.na(dados$Idade),] # verificando se existem idades com valor na
median(dados$Idade) # calculando mediana
dados[dados$Idade<0 | dados$Idade>110,]$Idade = median(dados$Idade)
dados[dados$Idade<0 | dados$Idade>110,]$Idade
summary(dados$Idade)
```

